apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: auramed-backend-service
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    spec:
      containers:
        - image: gcr.io/auramed-ai-prod/backend:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /live
          readinessProbe:
            httpGet:
              path: /ready
